name: Platform MOOC - Local
values:
  - key: baseUrl
    value: 'http://localhost:8080'
  - key: adminEmail
    value: admin@mooc.local
  - key: adminPassword
    value: Admin123!
  - key: teacherPassword
    value: Profesor2026
  - key: studentPassword
    value: Estudiante2026
  - key: videoSize
    value: '6000000'
