/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registro publico de estudiantes
         * @description Crea SIEMPRE una cuenta con rol `student`. El rol no se puede elegir:
         *     los profesores solo los crea un administrador.
         *     La respuesta es identica exista o no el correo, para impedir la
         *     enumeracion de cuentas. En `APP_ENV=dev` se incluye
         *     `dev_verification_token` para facilitar las pruebas.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /** @example {
                     *       "email": "estudiante@mooc.local",
                     *       "password": "Estudiante2026",
                     *       "full_name": "Estudiante Demo"
                     *     } */
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                        full_name: string;
                    };
                };
            };
            responses: {
                /** @description Solicitud aceptada */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirmar el correo con el token recibido */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /** @example {
                     *       "token": "pega-aqui-el-dev_verification_token-del-registro"
                     *     } */
                    "application/json": {
                        token: string;
                    };
                };
            };
            responses: {
                /** @description Cuenta verificada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar sesion */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /** @example {
                     *       "email": "admin@mooc.local",
                     *       "password": "Admin123!"
                     *     } */
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Sesion creada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access_token?: string;
                            /** @example Bearer */
                            token_type?: string;
                            expires_in?: number;
                            /** Format: uuid */
                            session_id?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Cuenta sin verificar o suspendida */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cerrar la sesion actual */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sesion cerrada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identidad de la sesion actual */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Datos del usuario */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar las sesiones activas propias */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de sesiones */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revocar una sesion propia
         * @description La revocacion es inmediata; tambien borra la cache en Redis.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sesion revocada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solicitar el restablecimiento de la contrasena */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Solicitud aceptada */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fijar una contrasena nueva
         * @description Revoca TODAS las sesiones abiertas del usuario.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Contrasena actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar usuarios */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de usuarios */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Crear un usuario (unica via para crear profesores) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /** @example {
                     *       "email": "profesora@mooc.local",
                     *       "full_name": "Profesora Demo",
                     *       "password": "Profesor2026",
                     *       "role": "teacher"
                     *     } */
                    "application/json": {
                        /** Format: email */
                        email: string;
                        full_name: string;
                        password: string;
                        /**
                         * @default teacher
                         * @enum {string}
                         */
                        role: "teacher" | "admin";
                    };
                };
            };
            responses: {
                /** @description Usuario creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description El correo ya existe */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cambiar rol o estado
         * @description Rechaza con 409 cualquier cambio que dejaria al sistema sin
         *     administradores activos. Suspender revoca las sesiones del usuario.
         *
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usuario actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Se protegio al ultimo administrador activo */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar la bitacora de auditoria */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lineas de auditoria */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar los cursos propios */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de cursos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Crear un curso (crea tambien su version 1 en borrador) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /** @example {
                     *       "title": "Fundamentos de la nube",
                     *       "summary": "Curso de prueba",
                     *       "category": "cloud",
                     *       "level": "beginner"
                     *     } */
                    "application/json": {
                        title: string;
                        summary?: string;
                        category?: string;
                        /** @enum {string} */
                        level?: "beginner" | "intermediate" | "advanced";
                        /** @default es */
                        language?: string;
                    };
                };
            };
            responses: {
                /** @description Curso creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar las versiones del curso */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de versiones */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Crear un borrador clonando la version vigente
         * @description Copia modulos, unidades, recursos y quizzes CONSERVANDO los
         *     `stable_id`. Como el progreso del estudiante apunta a `stable_id`,
         *     publicar la nueva version no borra su avance.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Borrador creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Ya existe un borrador abierto */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Previsualizar la version y ver si es publicable */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Esquema de la version y lista de problemas pendientes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publicar la version
         * @description Valida metadatos, estructura minima, criterios de aprobacion y
         *     disponibilidad de todos los recursos visibles. Si algo falla devuelve
         *     422 con la lista EXHAUSTIVA de problemas, no solo el primero.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Version publicada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description La version no cumple los requisitos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{id}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear un modulo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /** @example {
                     *       "title": "Modulo 1"
                     *     } */
                    "application/json": {
                        title: string;
                    };
                };
            };
            responses: {
                /** @description Modulo creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description La version esta publicada y es inmutable */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{id}/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear una unidad */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /** @example {
                     *       "title": "Unidad 1"
                     *     } */
                    "application/json": {
                        title: string;
                    };
                };
            };
            responses: {
                /** @description Unidad creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{id}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear un recurso */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /** @example {
                     *       "type": "rich_text",
                     *       "title": "Lectura inicial",
                     *       "content_md": "# Hola\n\nContenido de prueba.",
                     *       "required": true
                     *     } */
                    "application/json": {
                        /** @enum {string} */
                        type: "rich_text" | "image" | "video" | "audio" | "pdf" | "download" | "external_link" | "quiz";
                        title: string;
                        /** @default true */
                        required?: boolean;
                        /** @default true */
                        visible?: boolean;
                        /** @default false */
                        downloadable?: boolean;
                        content_md?: string;
                        external_url?: string;
                        /** Format: uuid */
                        asset_id?: string;
                    };
                };
            };
            responses: {
                /** @description Recurso creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Leer el contenido y su numero de revision */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Contenido en Markdown canonico */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Autosave del contenido
         * @description Si se envia `expected_revision` y no coincide con la revision actual,
         *     responde 409 en lugar de sobrescribir el trabajo de otro editor.
         *
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Guardado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflicto de edicion */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar una carga multipart directa al almacenamiento
         * @description Devuelve una URL prefirmada por cada parte. El cliente sube las partes
         *     DIRECTAMENTE al almacenamiento; los bytes nunca pasan por la API.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Carga iniciada con las URLs de cada parte */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description El archivo supera el maximo permitido */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado de la carga y partes que faltan
         * @description Consulta al ALMACENAMIENTO que partes llegaron de verdad y firma URLs
         *     nuevas solo para las faltantes. Esto es lo que hace reanudable la
         *     carga durante 24 horas.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Partes recibidas y faltantes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description La ventana de reanudacion expiro */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Cancelar la carga */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Carga cancelada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar la carga y encolar el procesamiento
         * @description Ensambla el objeto y publica el trabajo de escaneo. Es idempotente:
         *     reintentar devuelve el mismo resultado sin duplicar efectos.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Archivo recibido */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Faltan partes por subir */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del archivo */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Estado y metadatos del archivo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener una URL de entrega firmada
         * @description Verifica primero el derecho de acceso (propietario, administrador o
         *     estudiante con inscripcion activa) y solo entonces firma la URL.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description URL temporal de descarga o reproduccion */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description El archivo aun no esta listo */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/playlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista de reproduccion HLS con segmentos firmados
         * @description Devuelve el `.m3u8` reescrito: cada segmento lleva su propia URL
         *     prefirmada. Sin esto habria que abrir el bucket al publico.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de reproduccion */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.apple.mpegurl": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogo publico con busqueda, filtros y cursor */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    category?: string;
                    level?: string;
                    language?: string;
                    tag?: string;
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cursos publicados y `next_cursor` */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ficha publica del curso */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metadatos y esquema de contenidos visibles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar las inscripciones propias */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de inscripciones */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Inscribirse o reinscribirse
         * @description La reinscripcion reactiva la MISMA fila, de modo que el progreso y los
         *     intentos de quiz anteriores se conservan.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /** @example {
                     *       "slug": "fundamentos-de-la-nube"
                     *     } */
                    "application/json": {
                        slug: string;
                    };
                };
            };
            responses: {
                /** @description Inscripcion activa */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Curso no encontrado o no publicado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrollments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Retirarse del curso (sin perder el progreso) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Retiro registrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrollments/{id}/outline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contenido del curso con el avance de cada recurso */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Esquema */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reportar una senal de avance
         * @description El cliente envia SENALES (`open`, `heartbeat`, `complete`), nunca
         *     porcentajes. Si el cuerpo incluye `progress_pct` o `completed`, la
         *     peticion se rechaza con 422 y queda registrada en la auditoria.
         *     Un `complete` sin el tiempo minimo de permanencia tambien se rechaza.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /** @example {
                     *       "enrollment_id": "00000000-0000-0000-0000-000000000000",
                     *       "resource_stable_id": "00000000-0000-0000-0000-000000000000",
                     *       "event_type": "heartbeat",
                     *       "delta_secs": 30
                     *     } */
                    "application/json": {
                        /** Format: uuid */
                        enrollment_id: string;
                        /** Format: uuid */
                        resource_stable_id: string;
                        /** @enum {string} */
                        event_type: "open" | "heartbeat" | "complete";
                        position_secs?: number;
                        delta_secs?: number;
                    };
                };
            };
            responses: {
                /** @description Senal registrada y progreso recalculado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Senal rechazada */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vista del autor (incluye `is_correct`) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Quiz completo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Configurar intentos, tiempo, nota minima y retroalimentacion */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Quiz actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/quizzes/{id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear una pregunta de seleccion multiple (solo texto) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /** @example {
                     *       "prompt": "Que significa que la API sea sin estado?",
                     *       "options": [
                     *         {
                     *           "text": "Que no guarda datos en el contenedor entre peticiones",
                     *           "is_correct": true
                     *         },
                     *         {
                     *           "text": "Que no usa base de datos",
                     *           "is_correct": false
                     *         },
                     *         {
                     *           "text": "Que no responde nada",
                     *           "is_correct": false
                     *         }
                     *       ]
                     *     } */
                    "application/json": {
                        prompt: string;
                        /** @default 1 */
                        points?: number;
                        /** @default false */
                        multiple?: boolean;
                        options: {
                            text: string;
                            is_correct?: boolean;
                            feedback?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Pregunta creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Menos de dos opciones o sin respuesta correcta */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar un intento
         * @description Congela un snapshot del cuestionario. La respuesta NUNCA incluye
         *     `is_correct`. Si ya hay un intento abierto se devuelve ese mismo:
         *     recargar la pagina no consume un intento.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Intento (nuevo o el que estaba abierto) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Intentos agotados */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar un intento propio */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Estado del intento */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Guardado parcial de respuestas */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Respuestas guardadas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description El intento ya se envio o expiro */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/attempts/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enviar el intento y calificar en servidor */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resultado de la calificacion */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Ya hay una peticion en curso con esa llave */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/badges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Insignias propias */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de insignias con su URL de verificacion */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/badges/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verificacion publica de una insignia
         * @description Endpoint sin autenticacion. Devuelve el nombre del estudiante y el
         *     curso, nunca el correo ni identificadores internos.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Insignia valida o revocada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/badges/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revocar una insignia (administrador) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Insignia revocada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @enum {string} */
                code: "validation_error" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "unprocessable" | "payload_too_large" | "internal_error";
                message: string;
                details?: unknown;
                request_id?: string;
            };
        };
    };
    responses: {
        /** @description Peticion invalida */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Falta la sesion o es invalida */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description El rol no permite la operacion */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No existe, o existe pero no es tuyo */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PathId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
