$kind: http-request
url: "{{baseUrl}}/api/v1/quizzes/{{quizId}}"
method: PATCH
headers:
  Content-Type: application/json
body:
  type: json
  content: |-
    {
      "max_attempts": 3,
      "pass_score": 60
    }
order: 18000
